language:python
sudo:enabled
services:
    -mysql
python:
    -"3.5"


# command to install dependencies
install:
    -pip install -r requirements.txt

script:
    python manage.py test
